<script setup lang="ts">
import AdminPanel from './AdminPanel.vue';
import CommunicationManagement from './CommunicationManagement.vue';
defineProps<{name:string;csrf?:string}>();
const view=new URLSearchParams(location.search).get('manage')||'';
const cards=[{title:'Communication users',description:'Manage members, company assignments, access and Communication Admin roles.',href:'/products/communication?manage=users',icon:'users',label:'Manage users'},{title:'Companies & communities',description:'Set up company communities and manage groups and their members.',href:'/products/communication?manage=communities',icon:'community',label:'Manage communities'},{title:'Invitations',description:'Invite colleagues and manage pending, accepted and revoked invitations.',href:'/products/communication?manage=invitations',icon:'invite',label:'Manage invitations'},{title:'Status & announcements',description:'Publish status updates and send announcements to company communities.',href:'/communication?section=Status',icon:'status',label:'Open status updates'},{title:'Conversation review',description:'Review employee conversations and files using read-only tools.',href:'/communication?action=review',icon:'review',label:'Review conversations'},{title:'Review log',description:'See administrator reviews and conversation or attachment access history.',href:'/communication?action=audit',icon:'log',label:'View review log'}];
const paths:Record<string,string>={users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m20 0v-2a4 4 0 0 0-3-4M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0m3-4a4 4 0 0 1 0 8',community:'M3 21V5h8v16m0-12h10v12M6 9h2m-2 4h2m6 0h4m-4 4h4M1 21h22',invite:'M3 5h18v14H3z m0 0 9 7 9-7',status:'M9 3a9 9 0 0 0-6 8m1 6a9 9 0 0 0 14 2m3-6A9 9 0 0 0 15 3M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',review:'M3 4h18v16H3z m9 0v16',log:'M5 3h14v18H5z m3 5h8m-8 4h8m-8 4h6'};
</script>
<template>
<section class="communication-product-overview"><header class="communication-product-heading"><div class="communication-product-identity"><span class="communication-product-icon">C</span><div><p class="eyebrow">COMPANY PRODUCT</p><h1>Communication</h1><p class="muted">Your conversations. Your people. Your workspace.</p></div></div><a class="button primary" href="/communication">Go to chats →</a></header>
<template v-if="!view||view==='overview'"><p class="eyebrow">MANAGE COMMUNICATION <span class="communication-admin-badge">Super Admin</span></p><div class="communication-product-cards"><article v-for="card in cards" :key="card.title"><a :href="card.href"><span class="communication-card-icon"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path :d="paths[card.icon]"/></svg></span><div><h2>{{card.title}}</h2><p>{{card.description}}</p><span>{{card.label}} →</span></div></a><a v-if="card.icon==='status'" class="communication-announcement-link" href="/communication?action=announcement">Send announcement →</a></article></div><p class="communication-product-note">Manage Communication here. Website administration handles website content, products, branding and shared employee accounts.</p></template>
<template v-else><a class="communication-overview-back" href="/products/communication?manage=overview">← Communication overview</a><AdminPanel v-if="view==='users'" communication-module :name="name" tagline="" :logo="null" :csrf="csrf"/><CommunicationManagement v-else-if="view==='communities'||view==='invitations'" :view="view" :csrf="csrf"/><p v-else class="muted">Choose a tool from the Communication overview.</p></template>
</section>
</template>