<?php
\Illuminate\Support\Facades\Route::get('/pms/service-worker.js',fn()=>response()->file(public_path('pms-assets/service-worker.js'),['Content-Type'=>'application/javascript','Service-Worker-Allowed'=>'/pms']));
use Illuminate\Support\Facades\Route;
use App\Modules\Pms\Http\Controllers\WorkspaceController;
use App\Modules\Pms\Http\Controllers\DepartmentController;
use App\Modules\Pms\Http\Controllers\RoleController;
require_once app_path('Modules/Pms/Http/Controllers/helpers.php');
Route::get('/pms/join/{token}',fn(\Illuminate\Http\Request $request)=>app(\App\Http\Controllers\PortalController::class)->index($request,'projects'));
Route::get('/pms/invitation/{token}',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'join'])->name('pms.invitations.join');
Route::post('/pms/invitation/{token}',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'completeJoin'])->name('pms.invitations.join.complete');
Route::get('/pms',[WorkspaceController::class,'page'])->name('pms.workspace');
Route::prefix('pms/api')->name('pms.')->middleware(\App\Modules\Pms\Http\Middleware\AuthorizeWorkspace::class)->group(function(){
 Route::get('projects/{project}/task-list', \App\Modules\Pms\Http\Controllers\ProjectTaskListController::class);
 Route::post('invitations/{token}/respond',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'respond']);
 Route::get('invitations',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'index']);
 Route::get('invitations/sent',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'sentList']);
 Route::get('invitations/received',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'receivedList']);
 Route::post('invitations',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'send']);
 Route::post('invitations/employees',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'inviteEmployee']);
 Route::post('tasks/{task}/invite',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'inviteToTask']);
 Route::get('tasks/{task}/invite-check',[\App\Modules\Pms\Http\Controllers\InvitationController::class,'checkInvitee']);

 Route::post('subtasks',[\App\Modules\Pms\Http\Controllers\SubtaskController::class,'store']);
 Route::get('subtasks/{id}',[\App\Modules\Pms\Http\Controllers\SubtaskController::class,'show']);
 Route::put('subtasks/{id}',[\App\Modules\Pms\Http\Controllers\SubtaskController::class,'update']);
 Route::delete('subtasks/{id}',[\App\Modules\Pms\Http\Controllers\SubtaskController::class,'destroy']);
 Route::get('settings/branding',[\App\Modules\Pms\Http\Controllers\BrandingSettingController::class,'edit'])->name('settings.branding.edit');
 Route::post('settings/branding',[\App\Modules\Pms\Http\Controllers\BrandingSettingController::class,'update']);
 Route::post('settings/mail/test',[\App\Modules\Pms\Http\Controllers\MailSettingController::class,'test']);
 Route::post('settings/realtime/test',[\App\Modules\Pms\Http\Controllers\RealtimeSettingController::class,'test']);
 Route::get('settings/mail',[\App\Modules\Pms\Http\Controllers\MailSettingController::class,'edit'])->name('settings.mail.edit');
 Route::post('settings/mail',[\App\Modules\Pms\Http\Controllers\MailSettingController::class,'update']);
 Route::get('settings/realtime',[\App\Modules\Pms\Http\Controllers\RealtimeSettingController::class,'edit'])->name('settings.realtime.edit');
 Route::post('settings/realtime',[\App\Modules\Pms\Http\Controllers\RealtimeSettingController::class,'update']);
 Route::get('projects/{projectId}/chat',[\App\Modules\Pms\Http\Controllers\ProjectChatController::class,'fetch']);
 Route::post('projects/{projectId}/chat',[\App\Modules\Pms\Http\Controllers\ProjectChatController::class,'send']);
 Route::post('projects/{projectId}/chat/seen',[\App\Modules\Pms\Http\Controllers\ProjectChatController::class,'markMessagesAsSeen']);
 Route::delete('project-chat/{id}',[\App\Modules\Pms\Http\Controllers\ProjectChatController::class,'delete']);
 Route::post('broadcasting/auth',fn(\Illuminate\Http\Request $request)=>\App\Modules\Pms\Services\PmsRealtime::authorize($request));
 Route::get('tasks/{task}/handoff',[\App\Modules\Pms\Http\Controllers\TaskHandoffController::class,'options']);
 Route::post('tasks/{task}/handoff',[\App\Modules\Pms\Http\Controllers\TaskHandoffController::class,'store']);
 Route::get('tasks/{task}/placement-options',[\App\Modules\Pms\Http\Controllers\TaskHandoffController::class,'placementOptions']);
 Route::post('tasks/{task}/place',[\App\Modules\Pms\Http\Controllers\TaskHandoffController::class,'place']);
 Route::get('tasks/{task}/assignees',[\App\Modules\Pms\Http\Controllers\TaskController::class,'assigneeOptions']);
 Route::get('submissions',[\App\Modules\Pms\Http\Controllers\SubmissionController::class,'getSubmission']);
 Route::post('submissions',[\App\Modules\Pms\Http\Controllers\SubmissionController::class,'store']);
 Route::post('submissions/status',[\App\Modules\Pms\Http\Controllers\SubmissionController::class,'updateStatus']);
 Route::delete('submissions/{id}',[\App\Modules\Pms\Http\Controllers\SubmissionController::class,'destroy']);
 Route::get('submission-details',[\App\Modules\Pms\Http\Controllers\SubmissionController::class,'getProjectOrTaskDetails']);
 Route::post('project-assignments',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'assignProjectToTeamLeaderAndMembers']);
 Route::delete('project-assignments',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'RemoveAssignUser']);
 foreach(['task-priority'=>'priorityUpdate','task-due-date'=>'taskDueDateUpdate','task-description'=>'TaskDescription']as $path=>$method)Route::post($path,function(\Illuminate\Http\Request $request)use($method){$request->validate(['task_id'=>'required|exists:pms_tasks,id']);$controller=app(\App\Modules\Pms\Http\Controllers\TaskController::class);$controller->show((string)$request->task_id);return $controller->$method($request);});
 Route::post('task-status',function(\Illuminate\Http\Request $request){$request->validate(['task_id'=>'required|exists:pms_tasks,id']);$c=app(\App\Modules\Pms\Http\Controllers\TaskController::class);$c->show((string)$request->task_id);return $c->StatusUpdate($request);});
 Route::post('task-approval',function(\Illuminate\Http\Request $request){
  $actor=\App\Modules\Pms\Services\PmsAuth::user();abort_unless($actor->hasRole('admin')||$actor->hasRole('project_manager')||$actor->hasRole('team_leader'),403);
  $request->validate(['task_id'=>'required|exists:pms_tasks,id']);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$request->task_id);
  return app(\App\Modules\Pms\Http\Controllers\TaskController::class)->taskApprovalUpdate($request);
 });
 Route::post('subtask-status',function(\Illuminate\Http\Request $request){$request->validate(['sub_task_id'=>'required|exists:pms_subtasks,id']);$subtask=\App\Modules\Pms\Models\Subtasks::findOrFail($request->sub_task_id);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$subtask->task_id);return app(\App\Modules\Pms\Http\Controllers\SubtaskController::class)->StatusUpdate($request);});
 Route::post('subtask-priority',function(\Illuminate\Http\Request $request){$request->validate(['sub_task_id'=>'required|exists:pms_subtasks,id']);$subtask=\App\Modules\Pms\Models\Subtasks::findOrFail($request->sub_task_id);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$subtask->task_id);return app(\App\Modules\Pms\Http\Controllers\SubtaskController::class)->priorityUpdate($request);});
 Route::post('subtask-due-date',function(\Illuminate\Http\Request $request){$request->validate(['sub_task_id'=>'required|exists:pms_subtasks,id']);$subtask=\App\Modules\Pms\Models\Subtasks::findOrFail($request->sub_task_id);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$subtask->task_id);return app(\App\Modules\Pms\Http\Controllers\SubtaskController::class)->subTaskDueDateUpdate($request);});
 Route::post('subtask-description',function(\Illuminate\Http\Request $request){$request->validate(['sub_task_id'=>'required|exists:pms_subtasks,id']);$subtask=\App\Modules\Pms\Models\Subtasks::findOrFail($request->sub_task_id);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$subtask->task_id);$request->merge(['task_id'=>$subtask->id]);return app(\App\Modules\Pms\Http\Controllers\SubtaskController::class)->SubTaskDescription($request);});
 Route::get('notifications',[\App\Modules\Pms\Http\Controllers\NotificationController::class,'index']);
 Route::post('notifications/read-all',[\App\Modules\Pms\Http\Controllers\NotificationController::class,'markAllAsRead']);
 Route::get('notifications/{notification}/open',[\App\Modules\Pms\Http\Controllers\NotificationController::class,'open']);
 Route::get('profile',[\App\Modules\Pms\Http\Controllers\ProfileController::class,'index']);
 Route::post('profile',[\App\Modules\Pms\Http\Controllers\ProfileController::class,'update']);
 Route::post('task-assignees/assign',function(\Illuminate\Http\Request $request){$request->validate(['task_id'=>'required|exists:pms_tasks,id']);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$request->task_id);return app(\App\Modules\Pms\Http\Controllers\TaskController::class)->assignTaskToUser($request);});
 Route::post('task-assignees/remove',function(\Illuminate\Http\Request $request){$request->validate(['task_id'=>'required|exists:pms_tasks,id']);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$request->task_id);return app(\App\Modules\Pms\Http\Controllers\TaskController::class)->RemoveAssignUser($request);});
 Route::post('subtask-approval',function(\Illuminate\Http\Request $request){$actor=\App\Modules\Pms\Services\PmsAuth::user();abort_unless($actor->hasRole('admin')||$actor->hasRole('project_manager')||$actor->hasRole('team_leader'),403);$request->validate(['subtask_id'=>'required|exists:pms_subtasks,id']);$subtask=\App\Modules\Pms\Models\Subtasks::findOrFail($request->subtask_id);app(\App\Modules\Pms\Http\Controllers\TaskController::class)->show((string)$subtask->task_id);$request->merge(['task_id'=>$subtask->task_id]);return app(\App\Modules\Pms\Http\Controllers\SubtaskController::class)->subTaskApprovalUpdate($request);});
 Route::get('realtime/config',fn()=>response()->json(\App\Modules\Pms\Services\PmsRealtime::clientConfig()));
 Route::get('dashboard/table',[\App\Modules\Pms\Http\Controllers\DashboardController::class,'index']);
 Route::get('dashboard',[\App\Modules\Pms\Http\Controllers\DashboardController::class,'dashboard']);
 Route::get('team-activity',[\App\Modules\Pms\Http\Controllers\DashboardController::class,'timeTrackingDashBoard']);
 Route::get('work-logs/export/{format}',[\App\Modules\Pms\Http\Controllers\ReportExportController::class,'workLogs']);
 Route::get('work-logs',[\App\Modules\Pms\Http\Controllers\SummaryController::class,'index']);
 Route::get('reports/export/{format}',[\App\Modules\Pms\Http\Controllers\ReportExportController::class,'download']);
 Route::get('reports',[\App\Modules\Pms\Http\Controllers\ReportController::class,'index']);
 Route::get('reports/overview',[\App\Modules\Pms\Http\Controllers\ReportController::class,'overview']);
 Route::get('reports/data',[\App\Modules\Pms\Http\Controllers\ReportController::class,'getReportData']);
 Route::get('reports/tasks',[\App\Modules\Pms\Http\Controllers\ReportController::class,'getTasks']);
 Route::get('reports/subtasks',[\App\Modules\Pms\Http\Controllers\ReportController::class,'getSubtasks']);
 Route::get('team-space',[\App\Modules\Pms\Http\Controllers\TeamSpaceController::class,'index']);
 Route::get('team-space/{department}',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'departmentBoard']);
 Route::post('timers/start',[\App\Modules\Pms\Http\Controllers\TimerLogController::class,'startTimer']);
 Route::post('timers/pause',[\App\Modules\Pms\Http\Controllers\TimerLogController::class,'pauseTimer']);
 Route::post('timers/stop',[\App\Modules\Pms\Http\Controllers\TimerLogController::class,'stopTimer']);
 Route::get('timers/running',[\App\Modules\Pms\Http\Controllers\TimerLogController::class,'checkRunningTimer']);
 Route::get('my-work',[\App\Modules\Pms\Http\Controllers\MyWorkController::class,'index'])->name('my-work.index');
 Route::post('tasks/{task}/comments',[\App\Modules\Pms\Http\Controllers\TaskIssueController::class,'comment']);
 Route::delete('comments/{comment}',[\App\Modules\Pms\Http\Controllers\TaskIssueController::class,'deleteComment']);
 Route::post('tasks/{task}/attachments',[\App\Modules\Pms\Http\Controllers\TaskIssueController::class,'attachments']);
 Route::delete('attachments/{attachment}',[\App\Modules\Pms\Http\Controllers\TaskIssueController::class,'deleteAttachment']);
 Route::delete('tasks/{id}',function(string $id){$controller=app(\App\Modules\Pms\Http\Controllers\TaskController::class);$controller->show($id);return $controller->destroy($id);});
 Route::get('tasks/{id}',[\App\Modules\Pms\Http\Controllers\TaskController::class,'show']);
 Route::post('projects/{project}/sprints',[\App\Modules\Pms\Http\Controllers\SprintController::class,'store']);
 Route::put('sprints/{sprint}',[\App\Modules\Pms\Http\Controllers\SprintController::class,'update']);
 Route::delete('sprints/{sprint}',[\App\Modules\Pms\Http\Controllers\SprintController::class,'destroy']);
 Route::post('projects/{id}/approval',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'updateProjectApprovalStatus']);
 Route::post('project-status',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'updateProjectStatus']);
 Route::delete('employees/{id}',[\App\Modules\Pms\Http\Controllers\EmployeeController::class,'destroy']);
 Route::get('employees',[\App\Modules\Pms\Http\Controllers\EmployeeController::class,'index']);
 Route::post('employees',[\App\Modules\Pms\Http\Controllers\EmployeeController::class,'store']);
 Route::get('employees/{id}',[\App\Modules\Pms\Http\Controllers\EmployeeController::class,'edit']);
 Route::post('employees/{id}',[\App\Modules\Pms\Http\Controllers\EmployeeController::class,'update']);
 Route::post('tasks',[\App\Modules\Pms\Http\Controllers\TaskController::class,'store']);
 Route::patch('tasks/{task}/board',[\App\Modules\Pms\Http\Controllers\TaskController::class,'boardUpdate']);
 Route::get('projects/{id}/edit',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'edit']);
 Route::post('projects/{id}',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'update']);
 Route::delete('projects/{id}',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'destroy']);
 Route::get('projects',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'index'])->name('projects.index');
 Route::post('projects',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'store'])->name('projects.store');
 Route::get('projects/{project}',[\App\Modules\Pms\Http\Controllers\ProjectController::class,'show'])->name('projects.show');
 Route::get('workflows',[\App\Modules\Pms\Http\Controllers\WorkflowController::class,'index']);
 Route::post('workflows',[\App\Modules\Pms\Http\Controllers\WorkflowController::class,'store']);
 Route::put('workflows/{workflow}',[\App\Modules\Pms\Http\Controllers\WorkflowController::class,'update']);
 Route::delete('workflows/{workflow}',[\App\Modules\Pms\Http\Controllers\WorkflowController::class,'destroy']);
 Route::get('permissions',[\App\Modules\Pms\Http\Controllers\PermissionController::class,'index']);
 Route::post('permissions',[\App\Modules\Pms\Http\Controllers\PermissionController::class,'store']);
 Route::post('permissions/{id}',[\App\Modules\Pms\Http\Controllers\PermissionController::class,'update']);
 Route::delete('permissions/{id}',[\App\Modules\Pms\Http\Controllers\PermissionController::class,'destroy']);
 Route::get('/',[WorkspaceController::class,'data']);
 foreach(['departments'=>DepartmentController::class,'roles'=>RoleController::class] as $resource=>$controller){Route::get($resource,[$controller,'index']);Route::post($resource,[$controller,'store']);Route::post($resource.'/{id}',[$controller,'update'])->whereNumber('id');Route::delete($resource.'/{id}',[$controller,'destroy'])->whereNumber('id');}
});

foreach([\App\Modules\Pms\Events\PmsNotificationBroadcast::class,\App\Modules\Pms\Events\GlobalUserEvent::class,\App\Modules\Pms\Events\ProjectChatMessageSent::class,\App\Modules\Pms\Events\DirectMessageChanged::class]as $event)\Illuminate\Support\Facades\Event::listen($event,fn($message)=>\App\Modules\Pms\Services\PmsRealtime::deliver($message));
