<?php
namespace App\Modules\Pms\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Modules\Pms\Services\PmsAccess;
use App\Modules\Pms\Models\User;
use App\Modules\Pms\Events\DirectMessageChanged;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
class DirectMessageController extends Controller {
 private function actor():int{PmsAccess::requirePermission(request(),'message-access');return auth()->id()??0;}
 private function contact(int $id):void {if($id===0)return;abort_unless(User::whereKey($id)->where('status',1)->where('is_active',true)->exists(),404);}
 private function pair(int $id){$actor=$this->actor();$this->contact($id);return DB::table('pms_ch_messages')->where(fn($q)=>$q->where(fn($q)=>$q->where('from_id',$actor)->where('to_id',$id))->orWhere(fn($q)=>$q->where('from_id',$id)->where('to_id',$actor)));}
 private function changed(int $from,int $to):void {try{\App\Modules\Pms\Services\PmsRealtime::publish(new DirectMessageChanged($from,$to));}catch(\Throwable $e){report($e);}}
 public function index(Request $request){$actor=$this->actor();$search=$request->validate(['search'=>'nullable|string|max:255'])['search']??'';$contacts=User::where('status',1)->where('is_active',true)->where('id','!=',$actor)->where('name','ilike','%'.$search.'%')->orderBy('name')->get(['id','name','profile_img']);if($actor!==0 && (!$search||str_contains(strtolower('Super Admin'),strtolower($search))))$contacts->prepend((object)['id'=>0,'name'=>'Super Admin','profile_img'=>null]);$favorites=DB::table('pms_ch_favorites')->where('user_id',$actor)->pluck('favorite_id');$unread=DB::table('pms_ch_messages')->where('to_id',$actor)->where('seen',false)->selectRaw('from_id,COUNT(*) as count')->groupBy('from_id')->pluck('count','from_id');return response()->json(['contacts'=>$contacts,'favorites'=>$favorites,'unread'=>$unread,'user_id'=>$actor]);}
 public function messages(Request $request,int $id){$request->validate(['before'=>'nullable|uuid']);$query=$this->pair($id);if($request->filled('before')){$cursor=$this->pair($id)->where('id',$request->before)->first();abort_unless($cursor,404);$query->where(fn($q)=>$q->where('created_at','<',$cursor->created_at)->orWhere(fn($q)=>$q->where('created_at',$cursor->created_at)->where('id','<',$cursor->id)));}$rows=$query->orderByDesc('created_at')->orderByDesc('id')->limit(31)->get();$more=$rows->count()>30;return response()->json(['messages'=>$rows->take(30)->reverse()->values()->map(function($m){if($m->attachment){$a=json_decode($m->attachment,true);$m->attachment=['name'=>$a['name'],'mime'=>$a['mime'],'url'=>url('/pms/api/direct-messages/'.$m->id.'/attachment')];}return $m;}),'has_more'=>$more]);}
 public function send(Request $request,int $id){$actor=$this->actor();$this->contact($id);abort_if($id===$actor,422);$v=$request->validate(['body'=>'nullable|required_without:file|string|max:5000','file'=>'nullable|required_without:body|file|max:153600|mimes:png,jpg,jpeg,gif,zip,rar,txt']);$attachment=null;if($request->hasFile('file')){$file=$request->file('file');$path=$file->store('pms/direct-attachments','local');$attachment=json_encode(['path'=>$path,'name'=>$file->getClientOriginalName(),'mime'=>$file->getMimeType()]);}$uuid=(string)Str::uuid();DB::table('pms_ch_messages')->insert(['id'=>$uuid,'from_id'=>$actor,'to_id'=>$id,'body'=>$v['body']??null,'attachment'=>$attachment,'seen'=>false,'created_at'=>now(),'updated_at'=>now()]);$this->changed($actor,$id);return response()->json(['message'=>'Message sent.','id'=>$uuid],201);}
 public function seen(int $id){$actor=$this->actor();$this->contact($id);$changed=DB::table('pms_ch_messages')->where('from_id',$id)->where('to_id',$actor)->where('seen',false)->update(['seen'=>true,'updated_at'=>now()]);if($changed)$this->changed($actor,$id);return response()->json(['message'=>'Messages marked read.']);}
 public function favorite(int $id){$actor=$this->actor();$this->contact($id);$q=DB::table('pms_ch_favorites')->where('user_id',$actor)->where('favorite_id',$id);if($q->exists())$q->delete();else DB::table('pms_ch_favorites')->insert(['id'=>(string)Str::uuid(),'user_id'=>$actor,'favorite_id'=>$id,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['message'=>'Favorites updated.']);}
 public function destroy(string $id){$actor=$this->actor();$m=DB::table('pms_ch_messages')->where('id',$id)->where('from_id',$actor)->first();abort_unless($m,404);DB::table('pms_ch_messages')->where('id',$id)->delete();if($m->attachment){$a=json_decode($m->attachment,true);if(isset($a['path']))Storage::disk('local')->delete($a['path']);}$this->changed($m->from_id,$m->to_id);return response()->json(['message'=>'Message deleted.']);}
 public function photos(int $id){$rows=$this->pair($id)->whereNotNull('attachment')->latest()->get()->filter(fn($m)=>str_starts_with(json_decode($m->attachment,true)['mime']??'','image/'))->map(fn($m)=>['id'=>$m->id,'url'=>url('/pms/api/direct-messages/'.$m->id.'/attachment')])->values();return response()->json(['photos'=>$rows]);}
 public function deleteConversation(int $id){$actor=$this->actor();$messages=$this->pair($id)->get();DB::transaction(fn()=>$this->pair($id)->delete());foreach($messages as $m){if($m->attachment){$a=json_decode($m->attachment,true);if(isset($a['path']))Storage::disk('local')->delete($a['path']);}}$this->changed($actor,$id);return response()->json(['message'=>'Conversation deleted for both participants.']);}
 public function attachment(string $id){$actor=$this->actor();$m=DB::table('pms_ch_messages')->where('id',$id)->where(fn($q)=>$q->where('from_id',$actor)->orWhere('to_id',$actor))->first();abort_unless($m&&$m->attachment,404);$a=json_decode($m->attachment,true);abort_unless(isset($a['path'])&&Storage::disk('local')->exists($a['path']),404);if(str_starts_with($a['mime']??'','image/'))return Storage::disk('local')->response($a['path'],$a['name'],['Content-Type'=>$a['mime'],'X-Content-Type-Options'=>'nosniff']);return Storage::disk('local')->download($a['path'],$a['name']??'attachment');}
}
