<script setup lang="ts">
import {ref,onMounted,onUnmounted} from 'vue';import {createPmsEcho} from './realtime';
const photos=ref<any[]|null>(null);const props=defineProps<{csrf?:string}>();const contacts=ref<any[]>([]),messages=ref<any[]>([]),selected=ref<any>(null),search=ref(''),body=ref(''),file=ref<File|null>(null),favorites=ref<number[]>([]),unread=ref<Record<string,number>>({}),actor=ref(0),busy=ref(false),error=ref(''),more=ref(false);let echo:any;
async function api(path:string,method='GET',data?:any){const form=data instanceof FormData;const r=await fetch('/pms/api/'+path,{method,headers:{Accept:'application/json','X-CSRF-TOKEN':props.csrf||'',...(form?{}:{'Content-Type':'application/json'})},body:data?(form?data:JSON.stringify(data)):undefined});const d=await r.json();if(!r.ok)throw Error(d.message||'Unable to load messages.');return d;}
async function loadContacts(){const d=await api('messages?search='+encodeURIComponent(search.value));contacts.value=d.contacts;favorites.value=d.favorites;unread.value=d.unread;actor.value=d.user_id;}
async function loadMessages(older=false){if(!selected.value)return;const id=selected.value.id;const d=await api('messages/'+id+(older&&messages.value.length?'?before='+messages.value[0].id:''));if(selected.value?.id!==id)return;messages.value=older?[...d.messages,...messages.value]:d.messages;more.value=d.has_more;await api('messages/'+id+'/seen','POST');unread.value[id]=0;}
async function choose(c:any){selected.value=c;photos.value=null;messages.value=[];await run(()=>loadMessages());}
async function run(fn:()=>Promise<void>){busy.value=true;error.value='';try{await fn();}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function send(){await run(async()=>{const f=new FormData();if(body.value.trim())f.append('body',body.value);if(file.value)f.append('file',file.value);await api('messages/'+selected.value.id,'POST',f);body.value='';file.value=null;await loadMessages();});}
async function showPhotos(){await run(async()=>{photos.value=(await api('messages/'+selected.value.id+'/photos')).photos;});}
async function deleteConversation(){if(confirm('Delete this conversation for both participants?'))await run(async()=>{await api('messages/'+selected.value.id,'DELETE');messages.value=[];photos.value=null;await loadContacts();});}
async function favorite(){await run(async()=>{await api('messages/'+selected.value.id+'/favorite','POST');await loadContacts();});}
async function remove(m:any){if(confirm('Delete this message?'))await run(async()=>{await api('direct-messages/'+m.id,'DELETE');await loadMessages();});}
onMounted(async()=>{await run(loadContacts);echo=await createPmsEcho(props.csrf||'');echo?.private('pms.direct.'+actor.value).listen('.pms.direct.changed',async()=>{await loadContacts();if(selected.value)await loadMessages();});});onUnmounted(()=>echo?.disconnect());
</script>
<template><section class="pms-direct"><aside><h2>Messages</h2><form @submit.prevent="run(loadContacts)"><input v-model="search" placeholder="Search employees" aria-label="Search employees"><button class="button">Search</button></form><button v-for="c in contacts" :key="c.id" class="pms-contact" :class="{active:selected?.id===c.id}" @click="choose(c)"><img v-if="c.profile_img" :src="c.profile_img" alt=""><span v-else class="pms-contact-avatar">{{c.name?.charAt(0)}}</span><strong>{{c.name}}</strong><span v-if="favorites.includes(c.id)">&#9733;</span><span v-if="unread[c.id]" class="pms-status-badge">{{unread[c.id]}}</span></button></aside><div class="pms-direct-thread"><p v-if="error" class="notice admin-error">{{error}}</p><template v-if="selected"><header><h2>{{selected.name}}</h2><button class="button" @click="favorite">{{favorites.includes(selected.id)?'Remove favorite':'Add favorite'}}</button><button class="button" @click="showPhotos">Shared photos</button><button class="button" @click="deleteConversation">Delete conversation</button></header><div v-if="photos" class="pms-shared-photos"><a v-for="p in photos" :key="p.id" :href="p.url" target="_blank" rel="noopener"><img :src="p.url" alt="Shared photo" style="width:80px;height:80px;object-fit:cover"></a><p v-if="!photos.length">No shared photos.</p><button class="button" @click="photos=null">Close photos</button></div><div class="pms-direct-messages"><button v-if="more" class="button" :disabled="busy" @click="run(()=>loadMessages(true))">Load older messages</button><article v-for="m in messages" :key="m.id" :class="{own:m.from_id===actor}"><p>{{m.body}}</p><template v-if="m.attachment"><img v-if="m.attachment.mime.startsWith('image/')" :src="m.attachment.url" :alt="m.attachment.name"><a :href="m.attachment.url">{{m.attachment.name}}</a></template><small>{{new Date(m.created_at).toLocaleString()}} {{m.from_id===actor?(m.seen?'Read':'Sent'):''}}</small><button v-if="m.from_id===actor" aria-label="Delete message" @click="remove(m)"><i aria-hidden="true" class="ti ti-trash"></i></button></article><p v-if="!messages.length&&!busy" class="muted">Start a conversation.</p></div><form @submit.prevent="send"><textarea v-model="body" placeholder="Write a message" maxlength="5000" aria-label="Message"></textarea><label>Attachment<input type="file" accept=".png,.jpg,.jpeg,.gif,.zip,.rar,.txt" @change="file=($event.target as HTMLInputElement).files?.[0]||null"></label><button class="button primary" :disabled="busy||(!body.trim()&&!file)">{{busy?'Sending...':'Send'}}</button></form></template><p v-else class="muted">Select an employee to open your private conversation.</p></div></section></template>
<style scoped>.pms-direct{display:grid;grid-template-columns:290px 1fr;min-height:70vh;border:1px solid var(--pms-border,#ddd);border-radius:12px;overflow:hidden;background:var(--pms-card,#fff)}.pms-direct>aside{padding:16px;border-right:1px solid #ddd}.pms-contact{display:flex;align-items:center;gap:10px;width:100%;padding:14px 4px;border:0;background:transparent;text-align:left;color:inherit}.pms-contact.active{background:#e8efff}.pms-contact img,.pms-contact-avatar{width:36px;height:36px;border-radius:50%;object-fit:cover}.pms-contact-avatar{display:grid;place-items:center;background:#e8efff;color:#3466c9}.pms-direct-thread{padding:20px;display:flex;flex-direction:column;min-width:0}.pms-direct-thread header{display:flex;justify-content:space-between}.pms-direct-messages{overflow:auto;max-height:55vh;flex:1;padding:16px}.pms-direct-messages article{width:fit-content;max-width:80%;background:#f0f2f5;color:#222;padding:12px;border-radius:10px;margin-bottom:12px}.pms-direct-messages article.own{margin-left:auto;background:#e8efff}.pms-direct-messages img{max-width:260px;max-height:240px;object-fit:contain;display:block}.pms-direct-messages small{display:block}.pms-direct-thread form{display:flex;gap:12px;align-items:center}.pms-direct-thread textarea{flex:1}.pms-direct-thread input[type=file]{max-width:170px}@media(max-width:750px){.pms-direct{grid-template-columns:1fr}.pms-direct>aside{max-height:220px;overflow:auto}.pms-direct-thread form{flex-wrap:wrap}}</style>