<script lang="ts">let openDialogs=0;let bodyOverflow="";</script>
<script setup lang="ts">
import {ref,onMounted,onBeforeUnmount} from 'vue';
defineProps<{title:string;subtitle?:string;wide?:boolean;size?:'sm'|'lg'|'xl'|'assignment';centered?:boolean}>();
const emit=defineEmits(['close']);const dialog=ref<HTMLElement|null>(null);let previous:HTMLElement|null=null;
function keys(e:KeyboardEvent){if(!dialog.value||e.defaultPrevented||document.activeElement?.closest('[role=dialog]')!==dialog.value)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();emit('close');}if(e.key==='Tab'){const nodes=Array.from(dialog.value.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]')).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
onMounted(()=>{if(openDialogs++===0){bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';}previous=document.activeElement as HTMLElement;dialog.value?.focus();document.addEventListener('keydown',keys);});onBeforeUnmount(()=>{if(--openDialogs===0)document.body.style.overflow=bodyOverflow;document.removeEventListener('keydown',keys);previous?.focus();});
</script>
<template><div class="pms-form-backdrop pms-source-backdrop" :class="{'is-centered':centered}" @click.self="emit('close')"><section ref="dialog" tabindex="-1" class="pms-source-dialog" :class="[size?'size-'+size:'',{'is-wide':wide}]" role="dialog" aria-modal="true" :aria-label="title"><header class="modal-header"><slot name="header"><div><h5 class="modal-title">{{title}}</h5><small v-if="subtitle" class="text-muted">{{subtitle}}</small></div><button type="button" class="pms-dialog-close" aria-label="Close" @click="emit('close')"><i aria-hidden="true" class="ti ti-x"></i></button></slot></header><div class="modal-body"><slot/></div><footer v-if="$slots.footer" class="modal-footer"><slot name="footer"/></footer></section></div></template>
