<script setup lang="ts">
import {ref,computed} from 'vue';
import {parseChatDate,conversationTime} from './chatTime';
import {callOutcome,callDuration,missedCall,type VoiceCall} from './callHistory';
const props=defineProps<{calls:VoiceCall[];userId:number;busy:boolean;nextPage:number|null;canCall:boolean;avatar:(id:number)=>string|null}>();
const emit=defineEmits<{more:[];start:[id:number];open:[id:number]}>();
const filter=ref(''),onlyMissed=ref(false),selectedId=ref('');
const otherId=(c:VoiceCall)=>c.caller_id===props.userId?c.callee_id:c.caller_id;
const otherName=(c:VoiceCall)=>c.caller_id===props.userId?c.callee_name:c.caller_name;
const visible=computed(()=>props.calls.filter(c=>(!onlyMissed.value||missedCall(c,props.userId))&&otherName(c).toLowerCase().includes(filter.value.toLowerCase())));
const selected=computed(()=>props.calls.find(c=>c.id===selectedId.value));
const timestamp=(c:VoiceCall)=>parseChatDate(c.created_at).toLocaleString([],{dateStyle:'medium',timeStyle:'short'});
</script>
<template>
<div class="comm-layout calls-layout" :class="{'call-selected':selected}">
<aside class="comm-sidebar"><div class="comm-conversation-heading"><h2>Calls</h2></div><input class="comm-filter" v-model="filter" aria-label="Search calls" placeholder="Search calls"><nav class="calls-filters" aria-label="Filter call history"><button :class="{selected:!onlyMissed}" @click="onlyMissed=false">All</button><button :class="{selected:onlyMissed}" @click="onlyMissed=true">Missed</button></nav><div class="comm-conversations calls-list"><article v-for="c in visible" :key="c.id" :class="{selected:selectedId===c.id}"><button class="call-row" @click="selectedId=c.id" :aria-label="'Call details: '+otherName(c)"><span class="comm-avatar"><img v-if="avatar(otherId(c))" :src="avatar(otherId(c))!" alt=""><span v-else>{{otherName(c).slice(0,1)}}</span></span><span class="call-copy"><strong :class="{missed:missedCall(c,userId)}">{{otherName(c)}}</strong><small :class="{missed:missedCall(c,userId)}"><span aria-hidden="true">{{c.caller_id===userId?'\u2197':'\u2199'}}</span> {{callOutcome(c,userId)}}<template v-if="c.answered_at"> &middot; {{callDuration(c)}}</template></small><time :title="timestamp(c)">{{conversationTime(c.created_at)}}</time></span><span v-if="c.unread&&c.callee_id===userId" class="unread-dot" aria-label="Unread missed call"></span></button><button class="call-back" :disabled="!canCall" :aria-label="'Call '+otherName(c)" title="Voice call" @click="emit('start',c.conversation_id)"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2z"/></svg></button></article><p v-if="busy" class="comm-empty-small" role="status">Loading calls...</p><p v-else-if="!visible.length" class="comm-empty-small">{{calls.length?'No matching calls.':'No calls yet. Start a voice call from a personal chat.'}}</p><button v-if="nextPage" class="calls-more" :disabled="busy" @click="emit('more')">Load older calls</button></div></aside>
<section v-if="selected" class="call-details"><button class="call-details-back" @click="selectedId=''">&larr; Back to calls</button><span class="call-detail-avatar"><img v-if="avatar(otherId(selected))" :src="avatar(otherId(selected))!" alt=""><span v-else>{{otherName(selected).slice(0,1)}}</span></span><h2>{{otherName(selected)}}</h2><p :class="{missed:missedCall(selected,userId)}">{{callOutcome(selected,userId)}}</p><p>{{selected.caller_id===userId?'Outgoing':'Incoming'}} voice call &middot; {{timestamp(selected)}}</p><p v-if="selected.answered_at">Duration: {{callDuration(selected)}}</p><div class="call-detail-actions"><button :disabled="!canCall" @click="emit('start',selected.conversation_id)">Voice call</button><button @click="emit('open',selected.conversation_id)">Open chat</button></div></section>
<section v-else class="comm-welcome calls-welcome"><span class="comm-welcome-icon"><svg width="38" height="38" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.5 2.1L8 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.5c.9.3 1.9.6 2.9.7a2 2 0 0 1 1.7 2z"/></svg></span><h2>Voice calls</h2><p>Call your colleagues or select a call to see its details.</p><p class="comm-welcome-note">Your incoming, outgoing and missed calls, all in one place.</p></section>
</div>
</template>
<style scoped>
.calls-filters{display:flex;gap:8px;padding:0 20px 15px}.calls-filters button{border:0;border-radius:18px;background:var(--rail);color:var(--muted);padding:7px 14px;cursor:pointer}.calls-filters .selected{background:var(--comm-soft);color:var(--comm-accent)}.calls-list article{display:flex;align-items:center;padding:0 16px 0 0;min-height:86px}.calls-list article.selected{background:var(--comm-soft)}.call-row{display:flex;align-items:center;gap:14px;flex:1;min-width:0;border:0;background:transparent;color:var(--text);padding:15px 20px;text-align:left;cursor:pointer}.call-copy{display:flex;flex-direction:column;gap:5px;min-width:0}.call-copy strong{font-size:15px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.call-copy small,.call-copy time{font-size:12px;color:var(--muted)}.missed{color:#e56876!important}.call-back{border:0;background:transparent;color:var(--comm-accent);padding:10px;cursor:pointer}.call-back:disabled{opacity:.4}.unread-dot{margin-left:auto;width:8px;height:8px;border-radius:50%;background:var(--comm-accent);flex-shrink:0}.calls-more{width:100%;padding:15px;color:var(--comm-accent);background:transparent;border:0;cursor:pointer}.call-details{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:30px;text-align:center;min-height:0;overflow:auto}.call-details h2{font:600 24px Arial,sans-serif}.call-details p{color:var(--muted);font-size:14px}.call-detail-avatar{display:grid;place-items:center;overflow:hidden;border-radius:50%;width:110px;height:110px;background:var(--comm-soft);color:var(--comm-accent);font-size:40px}.call-detail-avatar img{width:100%;height:100%;object-fit:cover}.call-detail-actions{display:flex;gap:12px;margin-top:16px}.call-detail-actions button{border:1px solid var(--line);border-radius:20px;padding:10px 18px;background:var(--comm-soft);color:var(--comm-accent);cursor:pointer}.call-detail-actions button:disabled{opacity:.5}.call-details-back{position:absolute;left:20px;top:20px;background:transparent;border:0;color:var(--comm-accent);cursor:pointer}@media(max-width:700px){.calls-welcome{display:none}.call-selected>.comm-sidebar{display:none}}
</style>
