<script setup lang="ts">
import {ref,computed,onMounted,watch} from 'vue';
const props=defineProps<{csrf?:string;view?:string}>();
const emit=defineEmits(['changed']);
const data=ref<any>(null),error=ref(''),message=ref(''),busy=ref(false),selectedCompanyIds=ref<number[]>([]),companyName=ref(''),editCompany=ref<number|null>(null),email=ref(''),inviteAdmin=ref(false),groupIds=ref<number[]>([]),link=ref(''),delivery=ref(''),editingGroup=ref<any>(null);
const companies=computed(()=>data.value?.companies||[]);
const companyGroups=computed(()=>data.value?.groups.filter((g:any)=>selectedCompanyIds.value.includes(g.company_id))||[]);
const groupPeople=computed(()=>data.value?.people.filter((p:any)=>(p.company_ids||[p.company_id]).includes(editingGroup.value?.company_id)&&p.is_active&&p.communication_access)||[]);
async function call(path:string,method='GET',body?:any){
 const r=await fetch('/communication/api'+path,{method,headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':props.csrf||''},body:body?JSON.stringify(body):undefined});const result=await r.json();if(!r.ok)throw new Error(Object.values(result.errors||{}).flat().join(' ')||result.message||'Unable to complete this action.');return result;
}
async function load(){data.value=await call('/management');if(!selectedCompanyIds.value.length&&data.value.companies.length===1)selectedCompanyIds.value=[data.value.companies[0].id];}
async function perform(action:()=>Promise<any>){busy.value=true;error.value='';try{const result=await action();message.value=result.message||'Saved.';await load();emit('changed');return result;}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function saveCompany(){const result=await perform(()=>call('/companies'+(editCompany.value?'/'+editCompany.value:''),'POST',{name:companyName.value}));if(result){companyName.value='';editCompany.value=null;selectedCompanyIds.value=[result.id];}}
async function invite(){link.value='';const result=await perform(()=>call('/invitations','POST',{email:email.value,company_ids:selectedCompanyIds.value,group_ids:groupIds.value,communication_admin:inviteAdmin.value}));if(result){link.value=result.acceptance_url;delivery.value=result.delivery_status;email.value='';}}
async function resend(i:any){link.value='';const result=await perform(()=>call('/invitations','POST',{email:i.email,company_ids:companyIds(i),group_ids:Array.isArray(i.group_ids)?i.group_ids:JSON.parse(i.group_ids||'[]'),communication_admin:i.communication_admin}));if(result){link.value=result.acceptance_url;delivery.value=result.delivery_status;}}
function companyIds(item:any):number[]{return Array.isArray(item.company_ids)?item.company_ids:JSON.parse(item.company_ids||'null')||[item.company_id];}
function companyNames(item:any){return companies.value.filter((c:any)=>companyIds(item).includes(c.id)).map((c:any)=>c.name).join(', ');}
watch(selectedCompanyIds,()=>{groupIds.value=groupIds.value.filter(id=>companyGroups.value.some((g:any)=>g.id===id));});
function editGroup(g:any){editingGroup.value=JSON.parse(JSON.stringify(g));}
async function saveGroup(){const g=editingGroup.value;const result=await perform(()=>call('/groups/'+g.id,'POST',{name:g.name,member_ids:g.member_ids}));if(result)editingGroup.value=null;}
async function deleteGroup(g:any){if(confirm('Delete this group and its messages?'))await perform(()=>call('/groups/'+g.id,'DELETE'));}
function status(i:any){return i.accepted_at?'Accepted':i.revoked_at?'Revoked':new Date(i.expires_at.replace(' ','T')+'Z')<new Date()?'Expired':'Pending';}
onMounted(()=>load().catch(e=>error.value=e.message));
</script>
<template>
<div class="communication-management">
<h2>{{view==='invitations'?'Invitations':view==='communities'?'Companies & communities':'Communities and onboarding'}}</h2><p class="muted">Every employee belongs to a company community. Invited people choose their password and join their assigned groups.</p>
<p v-if="error" class="notice admin-error" role="alert">{{error}}</p><p v-if="message" class="notice" role="status">{{message}}</p>
<template v-if="data">
<div class="comm-management-grid">
<section v-if="data.super&&view!=='invitations'"><h3>Company communities</h3><form class="admin-editor" @submit.prevent="saveCompany"><label>{{editCompany?'Rename community':'New company name'}}<input v-model="companyName" required maxlength="100" placeholder="Skyinfinit"></label><div class="editor-actions"><button class="button primary" :disabled="busy">{{editCompany?'Save name':'Create community'}}</button><button v-if="editCompany" type="button" class="button" @click="editCompany=null;companyName=''">Cancel</button></div></form><div class="admin-list"><article v-for="c in companies" :key="c.id"><strong>{{c.name}}</strong><button @click="editCompany=c.id;companyName=c.name">Rename</button></article></div></section>
<section v-if="view!=='communities'"><h3>Invite a colleague</h3><form class="admin-editor" @submit.prevent="invite"><fieldset><legend>Companies (select one or more)</legend><div class="comm-invite-companies"><label class="check" v-for="c in companies" :key="c.id"><input type="checkbox" v-model="selectedCompanyIds" :value="c.id">{{c.name}}</label></div><small>One account will join every selected company community.</small></fieldset><label>Email<input type="email" v-model="email" required maxlength="254" placeholder="colleague@company.com"></label><fieldset v-if="companyGroups.length"><legend>Groups to join (optional)</legend><label class="check" v-for="g in companyGroups" :key="g.id"><input type="checkbox" v-model="groupIds" :value="g.id">{{g.name}} &middot; {{companies.find((c:any)=>c.id===g.company_id)?.name}}</label></fieldset><label v-if="data.super" class="check"><input type="checkbox" v-model="inviteAdmin">Grant Communication Admin access for all assigned companies</label><small>Invitations expire in 7 days. Only Super Admin can grant admin roles.</small><button class="button primary" :disabled="busy||!selectedCompanyIds.length">{{busy?'Working...':'Send invitation'}}</button></form><div v-if="link" class="comm-invite-link"><label>Acceptance link<input readonly :value="link" @focus="($event.target as HTMLInputElement).select()"></label><small>{{delivery==='sent'?'Invitation submitted to the mail service.':'Email delivery was not confirmed. You can use this acceptance link.'}}</small></div></section>
</div>
<template v-if="view!=='communities'"><h3>Invitations</h3><div class="admin-list"><p v-if="!data.invitations.length" class="empty-state">No invitations yet.</p><article v-for="i in data.invitations" :key="i.id"><div><strong>{{i.email}}</strong><p class="muted">{{companyNames(i)}} &middot; {{status(i)}} &middot; Email: {{i.delivery_status}}</p></div><div class="row-actions" v-if="!i.accepted_at"><button :disabled="busy" @click="resend(i)">Resend</button><button v-if="!i.revoked_at" :disabled="busy" @click="perform(()=>call('/invitations/'+i.id+'/revoke','POST'))">Revoke</button></div></article></div>
</template><template v-if="view!=='invitations'"><h3>Groups</h3><form v-if="editingGroup" class="admin-editor" @submit.prevent="saveGroup"><label>Name<input required v-model="editingGroup.name" maxlength="100"></label><fieldset><legend>Members</legend><label class="check" v-for="p in groupPeople" :key="p.id"><input type="checkbox" v-model="editingGroup.member_ids" :value="p.id">{{p.name}}</label></fieldset><div class="editor-actions"><button class="button primary" :disabled="busy">Save group</button><button class="button" type="button" @click="editingGroup=null">Cancel</button></div></form><div class="admin-list"><p v-if="!data.groups.length" class="empty-state">Create groups from Communication &rarr; Chats &rarr; +.</p><article v-for="g in data.groups" :key="g.id"><div><strong>{{g.name}}</strong><p class="muted">{{companies.find((c:any)=>c.id===g.company_id)?.name}} &middot; {{g.member_ids.length}} members</p></div><div class="row-actions"><button @click="editGroup(g)">Edit members</button><button v-if="data.super" @click="deleteGroup(g)" :disabled="busy">Delete</button></div></article></div>
<h3>Company employees</h3><p class="muted" v-if="data.super"><a href="/products/communication?manage=users">Manage accounts, company assignments, and admin access &rarr;</a></p><div class="admin-list"><article v-for="p in data.people" :key="p.id"><div><strong>{{p.name}}</strong><p class="muted">{{p.email}} &middot; {{companyNames(p)}}</p></div><span class="muted">{{p.communication_admin?'Communication Admin':'Member'}} &middot; {{p.communication_access?'Access enabled':'No access'}}</span></article></div>
</template></template><p v-else-if="!error" class="muted">Loading onboarding...</p>
</div>
</template>