<script setup lang="ts">
import {ref,onBeforeUnmount} from 'vue';
const props=defineProps<{canPublishStory?:boolean;profile:{id:number;name:string;email:string;avatar_url:string|null};request:(path:string,method?:string,body?:any)=>Promise<any>}>();
const emit=defineEmits<{updated:[profile:{name:string},csrf:string];close:[];publishStory:[]}>();
const name=ref(props.profile.name),currentPassword=ref(''),password=ref(''),confirmation=ref(''),photo=ref<File|null>(null),preview=ref(props.profile.avatar_url||''),remove=ref(false),saving=ref(false),error=ref(''),success=ref('');
let objectUrl='';
function selectPhoto(event:Event){const selected=(event.target as HTMLInputElement).files?.[0];if(!selected)return;if(!['image/png','image/jpeg','image/webp'].includes(selected.type)||selected.size>2*1024*1024){error.value='Choose a PNG, JPEG or WebP image up to 2 MB.';return;}if(objectUrl)URL.revokeObjectURL(objectUrl);photo.value=selected;preview.value=objectUrl=URL.createObjectURL(selected);remove.value=false;error.value='';}
function removePhoto(){photo.value=null;preview.value='';remove.value=true;}
async function save(){saving.value=true;error.value='';success.value='';try{const form=new FormData();form.append('name',name.value);form.append('remove_photo',remove.value?'1':'0');if(photo.value)form.append('photo',photo.value);if(password.value){form.append('current_password',currentPassword.value);form.append('password',password.value);form.append('password_confirmation',confirmation.value);}const result=await props.request('/profile','POST',form);name.value=result.profile.name;currentPassword.value='';password.value='';confirmation.value='';photo.value=null;remove.value=false;preview.value=result.profile.avatar_url||'';success.value='Profile saved.';emit('updated',result.profile,result.csrf);}catch(e){error.value=(e as Error).message;}finally{saving.value=false;}}
onBeforeUnmount(()=>{if(objectUrl)URL.revokeObjectURL(objectUrl);});
</script>
<template>
<form class="comm-profile-editor" @submit.prevent="save"><h2>Your profile</h2><button v-if="canPublishStory" type="button" class="comm-primary" @click="emit('publishStory')">Publish story</button><p class="comm-muted">Your colleagues will see your name and profile photo.</p><div class="comm-profile-photo"><img v-if="preview" :src="preview" alt="Your profile photo"><span v-else>{{name.slice(0,1).toUpperCase()}}</span></div><div class="comm-photo-actions"><label>Change photo<input type="file" accept="image/png,image/jpeg,image/webp" aria-label="Profile photo" @change="selectPhoto"></label><button type="button" v-if="preview" @click="removePhoto">Remove photo</button></div><small class="comm-muted">PNG, JPEG or WebP &middot; Up to 2 MB</small><label>Your name<input v-model="name" required maxlength="100" autocomplete="name"></label><label>Email<input :value="profile.email" readonly type="email"></label><details class="comm-password-settings"><summary>Change password</summary><label>Current password<input v-model="currentPassword" type="password" autocomplete="current-password" :required="!!password"></label><label>New password<input v-model="password" type="password" minlength="12" maxlength="200" autocomplete="new-password"></label><label>Confirm new password<input v-model="confirmation" type="password" :required="!!password" autocomplete="new-password"></label><small class="comm-muted">Use at least 12 characters.</small></details><p v-if="error" class="comm-error" role="alert">{{error}}</p><p v-if="success" class="comm-profile-success" role="status">{{success}}</p><button class="comm-primary" :disabled="saving">{{saving?'Saving...':'Save profile'}}</button></form>
</template>