<script setup lang="ts">
import {ref,computed,onMounted,onBeforeUnmount,nextTick,watch} from 'vue';
import {parseChatDate} from './chatTime';
type Call={id:string;conversation_id:number;caller_id:number;callee_id:number;caller_name:string;callee_name:string;type:string;status:string;created_at:string;answered_at:string|null;ended_at:string|null};
type Signal={kind:string;call:Call;offer?:RTCSessionDescriptionInit;answer?:RTCSessionDescriptionInit;candidate?:RTCIceCandidateInit};
const props=defineProps<{userId:number;csrf:string;request:(path:string,method?:string,body?:any)=>Promise<any>;avatar:(id:number)=>string|null;online:boolean}>();
const emit=defineEmits<{open:[id:number]}>();
const minimized=ref(false);
const call=ref<Call|null>(null),offer=ref<RTCSessionDescriptionInit|null>(null),busy=ref(false),error=ref(''),muted=ref(false),historyOpen=ref(false),history=ref<Call[]>([]),nextPage=ref<number|null>(null),historyBusy=ref(false),remoteAudio=ref<HTMLAudioElement|null>(null),audioBlocked=ref(false),clock=ref(Date.now()),relay=ref(true);
let peer:RTCPeerConnection|null=null,local:MediaStream|null=null,remote:MediaStream|null=null,timeout:ReturnType<typeof setTimeout>|undefined,health:ReturnType<typeof setInterval>|undefined,clockTimer:ReturnType<typeof setInterval>|undefined,dead=false;
let toneAudio:AudioContext|null=null,toneTimer:ReturnType<typeof setInterval>|undefined;
function stopTone(){if(toneTimer)clearInterval(toneTimer);toneTimer=undefined;void toneAudio?.close().catch(()=>{});toneAudio=null;}
function ring(){if(toneTimer)return;try{toneAudio=new AudioContext();void toneAudio.resume().catch(()=>{});const beep=()=>{if(!toneAudio||toneAudio.state!=='running')return;for(const offset of [0,.35]){const oscillator=toneAudio.createOscillator(),gain=toneAudio.createGain();oscillator.frequency.value=480;gain.gain.value=.04;oscillator.connect(gain);gain.connect(toneAudio.destination);oscillator.start(toneAudio.currentTime+offset);oscillator.stop(toneAudio.currentTime+offset+.22);}};beep();toneTimer=setInterval(beep,2200);}catch{}}
const early=new Map<string,Signal[]>();let incomingCandidates:RTCIceCandidateInit[]=[],outgoingCandidates:RTCIceCandidateInit[]=[];
const incoming=computed(()=>call.value?.callee_id===props.userId&&call.value.status==='ringing');
const otherName=computed(()=>call.value?.caller_id===props.userId?call.value?.callee_name:call.value?.caller_name);
const otherId=computed(()=>call.value?.caller_id===props.userId?call.value?.callee_id:call.value?.caller_id);
function outcome(c:Call){return c.status==='cancelled'&&c.callee_id===props.userId?'Missed':c.status==='missed'?(c.callee_id===props.userId?'Missed':'No answer'):({ended:'Completed',rejected:'Declined',cancelled:'Cancelled',failed:'Failed',active:'Ongoing',connecting:'Connecting',ringing:'Ringing'} as Record<string,string>)[c.status]||c.status;}
function duration(c:Call){if(!c.answered_at)return '';const end=c.ended_at?parseChatDate(c.ended_at).getTime():clock.value;const seconds=Math.max(0,Math.floor((end-parseChatDate(c.answered_at).getTime())/1000));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}
const label=computed(()=>incoming.value?'Incoming voice call':call.value?.status==='ringing'?'Calling...':call.value?.status==='active'?duration(call.value):'Connecting...');
function reset(){stopTone();minimized.value=false;if(timeout)clearTimeout(timeout);if(health)clearInterval(health);peer?.close();peer=null;local?.getTracks().forEach(t=>t.stop());local=null;remote=null;call.value=null;offer.value=null;incomingCandidates=[];outgoingCandidates=[];muted.value=false;audioBlocked.value=false;busy.value=false;}
async function signal(kind:string,data:Record<string,any>={}){const id=call.value?.id;if(!id)return;return props.request('/calls/'+id+'/signal','POST',{kind,...data});}
async function drainCandidates(){if(!peer?.remoteDescription)return;for(const candidate of incomingCandidates.splice(0))await peer.addIceCandidate(candidate);}
async function play(){await nextTick();if(remoteAudio.value&&remote){remoteAudio.value.srcObject=remote;try{await remoteAudio.value.play();audioBlocked.value=false;}catch{audioBlocked.value=true;}}}
async function setup(){
 if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||!window.RTCPeerConnection)throw new Error('Voice calls need HTTPS (or localhost), a supported browser and microphone access.');
 const ice=await props.request('/calls/ice');relay.value=ice.relay;
 local=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});
 if(dead){local.getTracks().forEach(t=>t.stop());throw new Error('Call cancelled.');}
 peer=new RTCPeerConnection({iceServers:ice.iceServers});remote=new MediaStream();local.getTracks().forEach(t=>peer!.addTrack(t,local!));
 peer.ontrack=e=>{if(!remote?.getTracks().some(t=>t.id===e.track.id))remote?.addTrack(e.track);void play();};
 peer.onicecandidate=e=>{if(!e.candidate)return;const candidate=e.candidate.toJSON();if(call.value)void signal('candidate',{candidate}).catch(()=>{});else outgoingCandidates.push(candidate);};
 peer.onconnectionstatechange=()=>{const state=peer?.connectionState;if(state==='connected'){if(timeout)clearTimeout(timeout);void signal('connected').catch(e=>{error.value=(e as Error).message;void finish('failed');});}else if(state==='failed')void finish('failed');else if(state==='disconnected'){if(timeout)clearTimeout(timeout);timeout=setTimeout(()=>{if(peer?.connectionState!=='connected')void finish('failed');},15000);}};
}
function watchdog(){if(timeout)clearTimeout(timeout);timeout=setTimeout(()=>{if(call.value?.status==='ringing'){if(call.value.caller_id===props.userId)void finish('missed');else{reset();void sync();}}else if(call.value?.status==='connecting')void finish('failed');},call.value?.status==='ringing'?Math.max(1000,60000-(Date.now()-parseChatDate(call.value.created_at).getTime())):45000);if(health)clearInterval(health);health=setInterval(()=>{if(call.value&&['connecting','active'].includes(call.value.status))void signal('heartbeat').catch(()=>{error.value='Calling connection lost.';void finish('failed');});},25000);}
async function start(conversationId:number){if(call.value||busy.value)return;error.value='';busy.value=true;try{if(!props.online)throw new Error('Reconnect to chat before starting a call.');await setup();const description=await peer!.createOffer();await peer!.setLocalDescription(description);const result=await props.request('/calls','POST',{conversation_id:conversationId,type:'audio',offer:{type:'offer',sdp:peer!.localDescription!.sdp}});if(dead){await props.request('/calls/'+result.call.id+'/finish','POST',{status:'failed'});reset();return;}call.value=result.call;ring();for(const candidate of outgoingCandidates.splice(0))await signal('candidate',{candidate}).catch(()=>{});if(call.value?.id===result.call.id)watchdog();for(const event of early.get(result.call.id)||[])await receive(event);early.delete(result.call.id);}catch(e){error.value=mediaError(e);if(call.value)await finish('failed');else reset();}finally{busy.value=false;}}
function mediaError(e:unknown){const name=(e as DOMException).name;return name==='NotAllowedError'?'Microphone permission was denied. Allow microphone access in your browser.':name==='NotFoundError'?'No microphone was found. Connect a microphone and try again.':(e as Error).message||'Unable to start the voice call.';}
async function accept(){if(!incoming.value||busy.value||!offer.value)return;busy.value=true;error.value='';stopTone();try{await setup();await peer!.setRemoteDescription(offer.value);await drainCandidates();const answer=await peer!.createAnswer();await peer!.setLocalDescription(answer);const result=await signal('answer',{answer:{type:'answer',sdp:peer!.localDescription!.sdp}});call.value=result.call;watchdog();}catch(e){const message=mediaError(e);if(message.includes('already answered')||message.includes('expired'))reset();else await finish('failed');error.value=message;}finally{busy.value=false;}}
async function finish(status?:string){const c=call.value;if(!c)return;const chosen=status||(c.status==='ringing'?(c.caller_id===props.userId?'cancelled':'rejected'):'ended');reset();try{await props.request('/calls/'+c.id+'/finish','POST',{status:chosen});if(historyOpen.value)await loadHistory();}catch(e){error.value=(e as Error).message;}}
async function receive(event:Signal){if(dead)return;const c=event.call;if(!c||![c.caller_id,c.callee_id].includes(props.userId))return;
 if(event.kind==='incoming'){if(c.callee_id!==props.userId)return;if(call.value&&call.value.id!==c.id)return;call.value=c;offer.value=event.offer||null;ring();watchdog();return;}
 if(call.value?.id!==c.id){const list=early.get(c.id)||[];if(list.length<100)list.push(event);early.set(c.id,list);if(early.size>5)early.delete(early.keys().next().value!);if(event.kind==='finished'&&historyOpen.value)void loadHistory();return;}
 if(event.kind==='finished'){reset();if(historyOpen.value)void loadHistory();return;}
 if(event.kind==='candidate'&&event.candidate){incomingCandidates.push(event.candidate);try{await drainCandidates();}catch{error.value='Unable to connect the voice call.';}return;}
 if(event.kind==='answer'&&event.answer&&peer){stopTone();try{call.value=c;await peer.setRemoteDescription(event.answer);await drainCandidates();watchdog();}catch(e){error.value=mediaError(e);await finish('failed');}return;}
 if(event.kind==='connected'){stopTone();call.value=c;}
}
async function sync(){if(busy.value)return;try{const state=await props.request('/calls/state');if(busy.value)return;if(!state.call){if(call.value)reset();return;}if(call.value?.id===state.call.id){call.value=state.call;return;}if(state.call.callee_id===props.userId&&state.call.status==='ringing'){await receive({kind:'incoming',call:state.call,offer:state.offer});for(const event of early.get(state.call.id)||[])await receive(event);early.delete(state.call.id);}else await props.request('/calls/'+state.call.id+'/finish','POST',{status:'failed'});}catch(e){error.value=(e as Error).message;}}
async function loadHistory(older=false){if(historyBusy.value)return;historyBusy.value=true;try{const result=await props.request('/calls'+(older&&nextPage.value?'?page='+nextPage.value:''));history.value=older?[...history.value,...result.calls]:result.calls;nextPage.value=result.next_page;}catch(e){error.value=(e as Error).message;}finally{historyBusy.value=false;}}
function openHistory(){historyOpen.value=true;void loadHistory();}
function mute(){muted.value=!muted.value;local?.getAudioTracks().forEach(t=>t.enabled=!muted.value);}
function unload(){const c=call.value;if(c)void fetch('/communication/api/calls/'+c.id+'/finish',{method:'POST',keepalive:true,headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':props.csrf},body:JSON.stringify({status:c.status==='ringing'?(c.caller_id===props.userId?'cancelled':'rejected'):'ended'})}).catch(()=>{});reset();}
watch(()=>props.online,value=>{if(value)void sync();});
onMounted(()=>{void sync();clockTimer=setInterval(()=>clock.value=Date.now(),1000);window.addEventListener('pagehide',unload);});
onBeforeUnmount(()=>{dead=true;unload();if(clockTimer)clearInterval(clockTimer);window.removeEventListener('pagehide',unload);});
defineExpose({start,receive,sync,openHistory,busy,call});
</script>
<template>
<p v-if="error" class="voice-error" role="alert">{{error}} <button @click="error=''" aria-label="Dismiss calling error">&times;</button></p>
<Teleport to="body"><section v-if="call" class="voice-overlay" :class="{minimized}" role="dialog" :aria-modal="!minimized" aria-label="Voice call"><div class="voice-card"><button v-if="!incoming" class="voice-minimize" :aria-label="minimized?'Restore voice call':'Minimize voice call'" @click="minimized=!minimized">{{minimized?'Restore':'Minimize'}}</button><span class="voice-avatar"><img v-if="otherId&&avatar(otherId)" :src="avatar(otherId)!" alt=""><template v-else>{{otherName?.slice(0,1)}}</template></span><h2>{{otherName}}</h2><p aria-live="polite">{{label}}</p><small v-if="!relay&&!incoming">Direct connection mode</small><audio ref="remoteAudio" autoplay/><button v-if="audioBlocked" @click="play">Enable call audio</button><div class="voice-controls"><button v-if="incoming" class="voice-accept" :disabled="busy" @click="accept">{{busy?'Connecting...':'Accept'}}</button><button v-if="!incoming&&call.status!=='ringing'" :aria-pressed="muted" @click="mute">{{muted?'Unmute':'Mute microphone'}}</button><button class="voice-end" :disabled="busy" @click="finish()">{{incoming?'Decline':call.status==='ringing'?'Cancel':'End call'}}</button></div></div></section>
<section v-if="historyOpen" class="voice-history-overlay" role="dialog" aria-modal="true" aria-label="Call history"><div class="voice-history"><header><h2>Calls</h2><button @click="historyOpen=false" aria-label="Close call history">&times;</button></header><p v-if="!history.length&&!historyBusy">No calls yet. Start a voice call from a personal chat.</p><article v-for="c in history" :key="c.id"><span class="voice-history-avatar"><img v-if="avatar(c.caller_id===userId?c.callee_id:c.caller_id)" :src="avatar(c.caller_id===userId?c.callee_id:c.caller_id)!" alt=""><template v-else>{{(c.caller_id===userId?c.callee_name:c.caller_name).slice(0,1)}}</template></span><div><strong>{{c.caller_id===userId?c.callee_name:c.caller_name}}</strong><p :class="{missed:['missed','cancelled'].includes(c.status)&&c.callee_id===userId}">{{c.caller_id===userId?'Outgoing':'Incoming'}} &middot; {{outcome(c)}} <span v-if="c.answered_at">&middot; {{duration(c)}}</span></p><time>{{parseChatDate(c.created_at).toLocaleString()}}</time></div><button :disabled="!!call||busy||!online" aria-label="Open chat to call back" title="Open chat" @click="historyOpen=false;emit('open',c.conversation_id)"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 4h16v12H9l-5 4V4"/></svg></button></article><p v-if="historyBusy" role="status">Loading calls...</p><button v-if="nextPage" :disabled="historyBusy" @click="loadHistory(true)">Load older calls</button></div></section></Teleport>
</template>
<style scoped>
.voice-error{position:fixed;top:76px;right:20px;max-width:420px;z-index:140;background:#572e2e;color:#fff;padding:12px 16px;border-radius:10px}.voice-error button{margin-left:12px}.voice-overlay,.voice-history-overlay{position:fixed;inset:0;background:#000b;z-index:130;display:flex;align-items:center;justify-content:center;padding:20px}.voice-card,.voice-history{background:var(--rail,#202020);color:var(--text,#eee);border:1px solid var(--line,#383838);border-radius:20px;padding:32px;width:min(440px,100%);box-shadow:0 24px 80px #0008}.voice-card{text-align:center;position:relative}.voice-minimize{position:absolute;top:12px;right:16px;border:0;background:transparent;color:inherit;cursor:pointer;font-size:12px}.voice-overlay.minimized{inset:auto 16px 16px auto;padding:0;background:transparent;width:min(360px,calc(100vw - 32px))}.minimized .voice-card{padding:28px 18px 18px}.minimized .voice-avatar{width:42px;height:42px;font-size:18px}.minimized .voice-card h2{font-size:18px;margin:8px 0}.minimized .voice-controls{margin-top:12px}.minimized .voice-controls button{padding:8px 12px;font-size:12px}.voice-avatar{display:inline-flex;width:100px;height:100px;align-items:center;justify-content:center;border-radius:50%;background:#18312b;color:#18b898;font-size:38px;overflow:hidden}.voice-avatar img,.voice-history-avatar img{width:100%;height:100%;object-fit:cover}.voice-card h2{font-family:inherit;margin:20px 0 10px;font-size:25px}.voice-controls{display:flex;gap:14px;justify-content:center;margin-top:30px;flex-wrap:wrap}.voice-controls button{padding:12px 18px;border-radius:24px;border:1px solid #666;background:#333;color:white;cursor:pointer}.voice-controls .voice-accept{background:#008f73;border-color:#008f73}.voice-controls .voice-end{background:#b73443;border-color:#b73443}.voice-controls button:disabled{opacity:.5}.voice-history{width:min(580px,100%);max-height:85vh;overflow:auto;padding:24px}.voice-history header{display:flex;align-items:center;justify-content:space-between;margin-bottom:18px}.voice-history h2{font-family:inherit;margin:0}.voice-history header button{font-size:26px}.voice-history article{display:flex;gap:14px;align-items:center;padding:16px 0;border-bottom:1px solid var(--line,#383838)}.voice-history article>div{flex:1;min-width:0}.voice-history-avatar{display:flex;align-items:center;justify-content:center;flex-shrink:0;width:42px;height:42px;border-radius:50%;background:#18312b;color:#18b898;overflow:hidden}.voice-history p{font-size:13px;margin:6px 0;color:var(--muted,#aaa)}.voice-history time{font-size:12px;color:var(--muted,#aaa)}.voice-history .missed{color:#ef7884}.voice-history button{background:transparent;color:inherit;border:0;cursor:pointer}.voice-history button:disabled{opacity:.4}.voice-card small{color:#aaa}
</style>
